name: Generate ASCII ARTwork

on: 
  push

jobs:
   ascii_job:
     runs-on: ubuntu-latest
     steps:
        - name: checkout repo
          uses: actions/checkout@v5

        - name: List rep files
          run: ls -ltra 

        - name: executing shell script
          run: |
            chmod +x
            ./ascii-script.sh
        